default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bills_dev

test:
  <<: *default
  database: bills_test

production:
  <<: *default
  database: bills_prod
